services:
  eshopservice:
    image: ${DOCKER_REGISTRY}eshopservice
    build:
      context: .
      dockerfile: EShopService\Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;

  userService:
    image: ${DOCKER_REGISTRY}userservice
    build:
      context: .
      dockerfile: UserService\Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mssql_data: